### ISSUE TITLE
Bug encountered when generating Chinese characters with my own dataset

### ISSUE THREAD

**Issue by HarperHao** [Hxyz-123/Font-diff#3]
Hello,
When I was sampling with my own dataset, I ran into the following bug:
<hr>

```
Traceback (most recent call last):
  File "sample.py", line 215, in <module>
    main()
  File "sample.py", line 159, in main
    sample = sample_fn(
  File "/home/amax/Lv/Font-diff-main/utils/gaussian_diffusion.py", line 466, in ddim_sample_loop
    for sample in self.ddim_sample_loop_progressive(
  File "/home/amax/Lv/Font-diff-main/utils/gaussian_diffusion.py", line 513, in ddim_sample_loop_progressive
    out = self.ddim_sample(
  File "/home/amax/Lv/Font-diff-main/utils/gaussian_diffusion.py", line 416, in ddim_sample
    out = self.p_mean_variance(
  File "/home/amax/Lv/Font-diff-main/utils/respace.py", line 64, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/amax/Lv/Font-diff-main/utils/gaussian_diffusion.py", line 181, in p_mean_variance
    model_output = model(x, self._scale_timesteps(t), **model_kwargs)
  File "/home/amax/Lv/Font-diff-main/utils/respace.py", line 101, in __call__
    return self.model(x, new_ts, **kwargs)
  File "sample.py", line 140, in model_fn
    model_output = model(x_t, ts, **model_kwargs)
  File "/home/amax/anaconda3/envs/diff_font/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amax/Lv/Font-diff-main/utils/unet.py", line 591, in forward
    label_emb[~mask_y] = self.label_emb(y[~mask_y])
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```
<hr>
My test_cfg.yaml file: <br><br>

```
dropout: 0.1
chara_nums: 2799
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 128
num_channels: 128
num_res_blocks: 3
batch_size: 5
num_samples: 10
attention_resolutions: '40, 20, 10'
use_ddim: True
timestep_respacing: ddim25
stroke_path: './chinese_stroke.txt'
model_path: './trained_models/model800000.pt'
sty_img_path: '../OTM/dataset_font/val/fzbangshu/0003.jpg'
total_txt_file: './total_chn.txt'
gen_txt_file: './gen_char.txt'
img_save_path: './result'
classifier_free: True
cont_scale: 3.0
sk_scale: 3.0
```

It is the wrong setting of the test_cfg.yaml?
Hope to get your help.

**Comment by HarperHao** [comment]
I found the reason: I don't have enough video memory（My video memory is 24GB）

**Comment by chenjingcheng** [comment]
i add  a line code ,then ok:
+chars_stroke = chars_stroke.to(dist_util.dev())
model_kwargs["stroke"] = chars_stroke[classes].to(dist_util.dev())

**Comment by ChenSiyi1** [comment]
> I found the reason: I don't have enough video memory（My video memory is 24GB），so I lowered the num_samples.Then it's ok!

Hi, I also met the same problem, but lowering the num_samples didn't work for me. Then I change the gen_char.txt to the total_chn.txt, it works! But, how to generate the specified text I want? Hope to get your help. Thank you!

**Comment by czzerone** [comment]
> I found the reason: I don't have enough video memory（My video memory is 24GB），so I lowered the num_samples.Then it's ok!

hello, can you please share your pretrained model for Chinese, Thank you!
